# version: '2'
# services:
#   zookeeper:
#     image: wurstmeister/zookeeper
#     ports:
#       - "2181:2181"
#   kafka:
#     image: bitnami/kafka:latest
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_ADVERTISED_HOST_NAME: 192.168.111.17
#       KAFKA_CREATE_TOPICS: "demoTopic"
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1 
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper